{
 "title": "LodzLove Dashboard YEEY",
 "description": "Łódź dla Łodzian",
 "tags": [
  "bb",
  "HACKATHON",
  "sprzedam opla"
 ],
 "time": { "from": "2019-09-28T20:16:59.910Z", "to": "2019-09-29T12:27:56.625Z" },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  { "title": "Panel Title", "type": "text", "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 }, "content": "\n# Lodz\n\n" },
  {
   "title": "List of Sensors",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n    Sensors.SensorID,\r\n    Sensors.SensorName,\r\n    Sensors.SensorDescription,\r\n    Sensors.Gps_latitude,\r\n    Sensors.Gps_longitude,\r\n\tMeasurements.MeasurementID,\r\n    Measurements.TypeID,\r\n    Measurements.Value,\r\n    Measurements.MeasurementDate as newest\r\nFROM \r\n\tMeasurements\r\nINNER JOIN Sensors on Sensors.SensorID = Measurements.SensorID\r\nwhere \r\n\tMeasurements.MeasurementDate in (\r\n        select maxdate \r\n            from(\r\n                    SELECT max(Measurements.MeasurementDate) as maxdate, Measurements.SensorID\r\n                    from Measurements \r\n                    GROUP by Measurements.SensorID\r\n                ) aa\r\n        )"
    }
   ]
  },
  {
   "title": "Najnowsza Temperatura Celciusze REAL Data",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT \r\n    Sensors.SensorID,\r\n    Sensors.SensorName,\r\n    Sensors.SensorDescription,\r\n    Sensors.Gps_latitude,\r\n    Sensors.Gps_longitude,\r\n\tMeasurementsReal.MeasurementID,\r\n    MeasurementsReal.TypeID,\r\n    MeasurementsReal.Value,\r\n    MeasurementsReal.MeasurementDate as newest\r\nFROM \r\n\tMeasurementsReal\r\nINNER JOIN Sensors on Sensors.SensorID = MeasurementsReal.SensorID\r\nwhere \r\n\tMeasurementsReal.MeasurementDate in (\r\n        select maxdate \r\n            from(\r\n                    SELECT max(MeasurementsReal.MeasurementDate) as maxdate, MeasurementsReal.SensorID\r\n                    from MeasurementsReal \r\n                    GROUP by MeasurementsReal.SensorID\r\n                ) aa\r\n        )\r\n        and TypeID=0"
    }
   ]
  },
  {
   "title": "Falcon Node 05 Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT \n  UNIX_TIMESTAMP(MeasurementsReal.MeasurementDate) as time_sec,\n    MeasurementsReal.Value As 'Node 05',\n    Sensors.SensorName\nFROM \n\tMeasurementsReal\nINNER JOIN Sensors on Sensors.SensorID = MeasurementsReal.SensorID\nWHERE $__timeFilter(MeasurementsReal.MeasurementDate) and MeasurementsReal.TypeId = 0 and MeasurementsReal.SensorID=5\nORDER BY MeasurementsReal.MeasurementDate ASC\n"
    }
   ]
  },
  {
   "title": "Najnowsza Temperatura Celciusze MOCK Data",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 14 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "\r\nSELECT \r\n    Sensors.SensorID,\r\n    Sensors.SensorName,\r\n    Sensors.SensorDescription,\r\n    Sensors.Gps_latitude,\r\n    Sensors.Gps_longitude,\r\n\tMeasurements.MeasurementID,\r\n    Measurements.TypeID,\r\n    Measurements.Value\r\nFROM \r\n\tMeasurements\r\nINNER JOIN Sensors on Sensors.SensorID = Measurements.SensorID\r\nwhere \r\n\tMeasurements.MeasurementDate in (\r\n        select maxdate \r\n            from(\r\n                    SELECT max(Measurements.MeasurementDate) as maxdate, Measurements.SensorID\r\n                    from Measurements \r\n                    GROUP by Measurements.SensorID\r\n                ) aa\r\n        )"
    }
   ]
  },
  {
   "title": "Falcon Node 05 Noice",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "dB", "label": "Noice" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  UNIX_TIMESTAMP(MeasurementsReal.MeasurementDate) as time_sec,\n    MeasurementsReal.Value As 'Falcon Node 05'\nFROM \n\tMeasurementsReal\nINNER JOIN Sensors on Sensors.SensorID = MeasurementsReal.SensorID\nWHERE $__timeFilter(MeasurementsReal.MeasurementDate) and MeasurementsReal.TypeId = 3 and MeasurementsReal.SensorID = 5\nORDER BY MeasurementsReal.MeasurementDate ASC"
    }
   ]
  },
  {
   "title": "Falcon Node 05 Lux",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 20 },
   "yaxes": [
    { "format": "lux", "label": "Lux" }
   ],
   "targets": [
    {
     "rawSql": "\nSELECT \n  UNIX_TIMESTAMP(MeasurementsReal.MeasurementDate) as time_sec,\n    MeasurementsReal.Value As 'Lux',\n    Sensors.SensorName\nFROM \n\tMeasurementsReal\nINNER JOIN Sensors on Sensors.SensorID = MeasurementsReal.SensorID\nWHERE $__timeFilter(MeasurementsReal.MeasurementDate) and MeasurementsReal.TypeId = 2 and MeasurementsReal.SensorID=5\nORDER BY MeasurementsReal.MeasurementDate ASC\n"
    }
   ]
  }
 ]
}